apiVersion: v1
kind: Service
metadata:
  name: weather-app-service
  namespace: weather-app-namespace
spec:
  selector:
    app: weather-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 32000  # Picked a new available port in the range 30000-32767
  type: NodePort
