apiVersion: v1
kind: Service
metadata:
  name: weather-app-service
  namespace: weather-app-namespace
spec:
  selector:
    app: weather-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
