apiVersion: v1
kind: Service
metadata:
  name: weather-app-service
spec:
  type: NodePort  # Exposes app on a port
  selector:
    app: weather-app
  ports:
    - protocol: TCP
      port: 80        # The port inside the cluster
      targetPort: 80  # The port inside the container
      nodePort: 30008  # The external port
